# Use official Python base image
FROM python:3.10

# Set working directory
WORKDIR /.

# Copy your code into the image
COPY . .

# Install dependencies (if any)
RUN pip install -r requirements.txt

# Run your script
CMD ["python", "app.py"]
